-- docs/supabase_setup.sql
-- =========================
-- ONE PASTE, THE WHOLE DATABASE. Creates every table the signed-in half
-- of TerraMeasure uses, in the right order, with row-level security.
--
-- HOW TO USE
--   1. Open your Supabase project, click "SQL Editor" in the sidebar.
--   2. Click "New query", paste this ENTIRE file, click "Run".
--   3. You should see "Success. No rows returned". That is what success
--      looks like for a script that only creates things.
--
-- SAFE TO RUN TWICE. Every statement is idempotent: tables use
-- "create table if not exists", and each policy is dropped before it is
-- created, so re-running never errors and never wipes data.
--
-- WHAT IF I NEVER RUN IT? The app still works. Saving a survey writes to
-- the device first and always succeeds; this file only adds the CLOUD
-- copy, so saves follow a signed-in person to their other devices, and
-- it switches on the Ground Truth page. Nothing here is required to
-- measure land.
--
-- WHAT THIS FILE REPLACES: docs/reports_table.sql (already run, kept for
-- reference) covered the public share links, which the BACKEND writes
-- with its secret key. This file covers the three tables the BROWSER
-- touches: profiles, surveys, ground_truth.

-- ---------------------------------------------------------------------
-- 1. profiles: one row per account, holding the display name.
-- ---------------------------------------------------------------------
-- Why a separate table instead of using the auth user record? Because
-- auth.users is managed by Supabase and is not readable from the
-- browser. A tiny mirror table with its own security rules is the
-- standard pattern.
create table if not exists public.profiles (
    id   uuid primary key references auth.users (id) on delete cascade,
    name text
);

alter table public.profiles enable row level security;

-- auth.uid() is "the user id inside the caller's login token". Every
-- policy below compares it to the row's owner, so the public anon key
-- shipped in the frontend can only ever touch that person's own data.
drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
    on public.profiles for select
    using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
    on public.profiles for insert
    with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
    on public.profiles for update
    using (auth.uid() = id)
    with check (auth.uid() = id);

-- Give every NEW account a profile row automatically. A trigger is a bit
-- of code the database runs itself when something happens; this one
-- fires the moment Supabase creates an account.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, name)
    values (
        new.id,
        -- Prefer a name the sign-up form or Google supplied; otherwise
        -- use the part of the email before the @.
        coalesce(
            new.raw_user_meta_data ->> 'name',
            new.raw_user_meta_data ->> 'full_name',
            split_part(new.email, '@', 1)
        )
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- Existing accounts created before this file was run get a row too, so
-- nobody is left without a profile.
insert into public.profiles (id, name)
select u.id, split_part(u.email, '@', 1)
from auth.users u
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- 2. surveys: the cloud copy of a saved survey.
-- ---------------------------------------------------------------------
-- Only the SUMMARY is stored, never the elevation grid: where it was,
-- how big, what it scored, and which data source produced it. That is
-- everything the saved list needs, and it keeps rows tiny.
--
-- The id is a bigint (a plain auto-incrementing number) on purpose:
-- ground_truth.survey_id below points at it and must match that type.
create table if not exists public.surveys (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references auth.users (id) on delete cascade,
    lat         double precision not null,
    lon         double precision not null,
    score       double precision,
    area_acres  double precision,
    source      text,
    surveyed_at timestamptz default now()
);

alter table public.surveys enable row level security;

drop policy if exists "Users can insert their own surveys" on public.surveys;
create policy "Users can insert their own surveys"
    on public.surveys for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can view their own surveys" on public.surveys;
create policy "Users can view their own surveys"
    on public.surveys for select
    using (auth.uid() = user_id);

drop policy if exists "Users can delete their own surveys" on public.surveys;
create policy "Users can delete their own surveys"
    on public.surveys for delete
    using (auth.uid() = user_id);

-- The one query the app runs is "my surveys, newest first".
create index if not exists surveys_user_time_idx
    on public.surveys (user_id, surveyed_at desc);

-- ---------------------------------------------------------------------
-- 3. ground_truth: what a surveyor ACTUALLY measured on site.
-- ---------------------------------------------------------------------
-- This is the accuracy feedback loop and, over time, the part of the
-- product nobody can copy: real field measurements next to our
-- predictions, which tell us where the model runs hot or cold.
-- (Same content as docs/ground_truth_table.sql, included here so this
-- one file is all you ever need to paste.)
create table if not exists public.ground_truth (
    id                     uuid primary key default gen_random_uuid(),
    user_id                uuid not null references auth.users (id) on delete cascade,
    -- The saved survey this visit corrects, or null when the surveyor
    -- typed coordinates by hand. "on delete set null" means deleting a
    -- saved survey keeps the field data and only blanks the link.
    survey_id              bigint references public.surveys (id) on delete set null,
    lat                    double precision,
    lon                    double precision,
    measured_slope_deg     double precision,
    measured_elev_range_ft double precision,
    field_verdict          text,   -- "go" | "caution" | "no-go"
    notes                  text,
    visited_on             date,
    created_at             timestamptz default now()
);

alter table public.ground_truth enable row level security;

drop policy if exists "Users can insert their own ground truth" on public.ground_truth;
create policy "Users can insert their own ground truth"
    on public.ground_truth for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can view their own ground truth" on public.ground_truth;
create policy "Users can view their own ground truth"
    on public.ground_truth for select
    using (auth.uid() = user_id);

create index if not exists ground_truth_user_created_idx
    on public.ground_truth (user_id, created_at desc);

-- ---------------------------------------------------------------------
-- Done. Reload TerraMeasure in the browser; Save now keeps a cloud copy
-- and the Ground Truth page can record site visits.
-- ---------------------------------------------------------------------
